# Generated by Django 3.0 on 2020-01-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_popcorn', '0003_accountprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='picture',
        ),
    ]
