# Generated by Django 3.0 on 2020-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_popcorn', '0004_remove_accountprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='watchedMovies',
            field=models.ManyToManyField(blank=True, related_name='watched', to='random_popcorn.Movie'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='random_popcorn.Movie'),
        ),
    ]
