# Generated by Django 3.0 on 2020-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_popcorn', '0005_auto_20200105_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='account_image'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
